// <auto-generated />
using System;
using CyberQuiz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberQuiz.UI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309162513_AddCreatedAtToApplicationUser")]
    partial class AddCreatedAtToApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Summer2024"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "P@ssw0rd"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "t7!Qv#9zL2@pX5"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "12345678"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Multi-Factor Authentication"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Managed File Access"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Main Firewall Agent"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Mobile Fast Approval"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "De gör att du kan återanvända samma lösenord överallt"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "De genererar och lagrar unika, starka lösenord"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "De stänger av MFA"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "De gör lösenord synliga för alla i teamet"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Gissa lösenord genom att prova alla kombinationer"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Återanvända läckta inloggningar på andra tjänster"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Skicka skadliga bilagor via e-post"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Avlyssna Wi-Fi med en router"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "SMS-kod"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "App-baserad engångskod eller säkerhetsnyckel"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Lösenordsfråga (”mors flicknamn”)"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Inget extra skydd behövs"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Mejlet har perfekt grammatik och korrekt domän"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Brådska/hot och en länk som ser konstig ut"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Det kommer alltid från en intern adress"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Det innehåller aldrig länkar"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Klicka snabbt för att se vad det är"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Svara och be om mer information"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Verifiera via officiell kanal och undvik länken"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Skicka länken till alla kollegor"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Massutskick till hela internet"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Riktad phishing mot en specifik person eller organisation"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Phishing via telefonledning (analog)"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Ett antivirusprogram"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Bilagor kan innehålla skadlig kod/makron"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Bilagor kan inte skada datorer"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Bilagor är alltid krypterade"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "PDF-filer är alltid säkra"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Lita på avsändarnamnet som visas"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Verifiera via en känd kontaktväg (t.ex. ring växeln)"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Klicka och logga in för att kontrollera"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Svar direkt och fråga om det är äkta"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "En fysisk kabeltyp"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "En logisk adress för en tjänst på en host"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Ett wifi-lösenord"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Ett operativsystem"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Krypterar all trafik automatiskt"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Översätter domännamn till IP-adresser"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Blockerar spammejl"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Skapar användarkonton"
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Tillåter/blockerar trafik enligt regler"
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Skapar starka lösenord"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Ökar internet-hastigheten"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Rensar cookies"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Alla ska ha admin för att slippa problem"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "Minsta möjliga behörighet för att göra jobbet"
                        },
                        new
                        {
                            Id = 55,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Ge alltid full åtkomst i testmiljö"
                        },
                        new
                        {
                            Id = 56,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Blockera alla användare"
                        },
                        new
                        {
                            Id = 57,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "FTP"
                        },
                        new
                        {
                            Id = 58,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "HTTP"
                        },
                        new
                        {
                            Id = 59,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "HTTPS"
                        },
                        new
                        {
                            Id = 60,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Telnet"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Att stoppa all phishing"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Avlyssning och manipulation av trafik i transit"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Att göra lösenord onödiga"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Att radera cookies automatiskt"
                        },
                        new
                        {
                            Id = 65,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "När databasen kraschar"
                        },
                        new
                        {
                            Id = 66,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "När attacker injicerar script som körs i användarens webbläsare"
                        },
                        new
                        {
                            Id = 67,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "När nätverket är långsamt"
                        },
                        new
                        {
                            Id = 68,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "När användaren glömmer lösenordet"
                        },
                        new
                        {
                            Id = 69,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "När man använder SQL Server"
                        },
                        new
                        {
                            Id = 70,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "Manipulera SQL-frågor via osanerad input"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "När man krypterar en tabell"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "När man indexerar en kolumn"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "Anti-forgery token / SameSite cookies"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Att slå av HTTPS"
                        },
                        new
                        {
                            Id = 75,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Att spara lösenord i localStorage"
                        },
                        new
                        {
                            Id = 76,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Att använda längre URL:er"
                        },
                        new
                        {
                            Id = 77,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Så att lösenord kan läsas enkelt vid support"
                        },
                        new
                        {
                            Id = 78,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "Om DB läcker ska lösenord inte kunna läsas i klartext"
                        },
                        new
                        {
                            Id = 79,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "För att göra inloggning långsammare"
                        },
                        new
                        {
                            Id = 80,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "För att slippa använda MFA"
                        });
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basprinciper och vanliga hot.",
                            Name = "Grundläggande cybersäkerhet"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nätverkssäkerhet och webbsäkerhet.",
                            Name = "Nätverk & webb"
                        });
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = "Längd + variation + inget ord i ordlista är bra.",
                            OrderIndex = 1,
                            SubCategoryId = 1,
                            Text = "Vilket lösenord är starkast?"
                        },
                        new
                        {
                            Id = 2,
                            Explanation = "MFA = Multi-Factor Authentication.",
                            OrderIndex = 2,
                            SubCategoryId = 1,
                            Text = "Vad betyder MFA?"
                        },
                        new
                        {
                            Id = 3,
                            Explanation = "De hjälper dig att ha unika, starka lösenord.",
                            OrderIndex = 3,
                            SubCategoryId = 1,
                            Text = "Varför är lösenordshanterare bra?"
                        },
                        new
                        {
                            Id = 4,
                            Explanation = "Återanvända läckta inloggningar på andra sajter.",
                            OrderIndex = 4,
                            SubCategoryId = 1,
                            Text = "Vad är 'credential stuffing'?"
                        },
                        new
                        {
                            Id = 5,
                            Explanation = "App-baserade engångskoder eller säkerhetsnyckel är bättre.",
                            OrderIndex = 5,
                            SubCategoryId = 1,
                            Text = "Vilken MFA-metod är oftast starkare än SMS?"
                        },
                        new
                        {
                            Id = 6,
                            Explanation = "Brådska + hot + konstig avsändare är vanligt.",
                            OrderIndex = 1,
                            SubCategoryId = 2,
                            Text = "Vilket är ett vanligt tecken på phishing?"
                        },
                        new
                        {
                            Id = 7,
                            Explanation = "Öppna inte länken; verifiera via officiell kanal.",
                            OrderIndex = 2,
                            SubCategoryId = 2,
                            Text = "Vad bör du göra om du får en misstänkt länk i ett mejl?"
                        },
                        new
                        {
                            Id = 8,
                            Explanation = "Riktad phishing mot en specifik person/grupp.",
                            OrderIndex = 3,
                            SubCategoryId = 2,
                            Text = "Vad är 'spear phishing'?"
                        },
                        new
                        {
                            Id = 9,
                            Explanation = "De kan innehålla skadlig kod/makron.",
                            OrderIndex = 4,
                            SubCategoryId = 2,
                            Text = "Varför är bilagor i okända mejl farliga?"
                        },
                        new
                        {
                            Id = 10,
                            Explanation = "Verifiera via en känd, oberoende kontaktväg.",
                            OrderIndex = 5,
                            SubCategoryId = 2,
                            Text = "Vilket är säkrast sätt att kontrollera om ett mejl är äkta?"
                        },
                        new
                        {
                            Id = 11,
                            Explanation = "En logisk adress för tjänster på en host.",
                            OrderIndex = 1,
                            SubCategoryId = 3,
                            Text = "Vad är en port (i nätverkssammanhang)?"
                        },
                        new
                        {
                            Id = 12,
                            Explanation = "Översätter domännamn till IP-adresser.",
                            OrderIndex = 2,
                            SubCategoryId = 3,
                            Text = "Vad gör DNS?"
                        },
                        new
                        {
                            Id = 13,
                            Explanation = "Tillåter/blockerar trafik enligt regler.",
                            OrderIndex = 3,
                            SubCategoryId = 3,
                            Text = "Vad gör en brandvägg (firewall) i enklaste form?"
                        },
                        new
                        {
                            Id = 14,
                            Explanation = "Minsta möjliga behörighet för att göra jobbet.",
                            OrderIndex = 4,
                            SubCategoryId = 3,
                            Text = "Vad innebär 'least privilege'?"
                        },
                        new
                        {
                            Id = 15,
                            Explanation = "HTTPS (HTTP över TLS).",
                            OrderIndex = 5,
                            SubCategoryId = 3,
                            Text = "Vilket protokoll används typiskt för krypterad webbtrafik?"
                        },
                        new
                        {
                            Id = 16,
                            Explanation = "Avlyssning och manipulation av trafik i transit.",
                            OrderIndex = 1,
                            SubCategoryId = 4,
                            Text = "Vad skyddar HTTPS främst mot?"
                        },
                        new
                        {
                            Id = 17,
                            Explanation = "När attacker injicerar script som körs i användarens webbläsare.",
                            OrderIndex = 2,
                            SubCategoryId = 4,
                            Text = "Vad är XSS (Cross-Site Scripting)?"
                        },
                        new
                        {
                            Id = 18,
                            Explanation = "Manipulera SQL-frågor via osanerad input.",
                            OrderIndex = 3,
                            SubCategoryId = 4,
                            Text = "Vad är SQL-injection?"
                        },
                        new
                        {
                            Id = 19,
                            Explanation = "Anti-forgery token / SameSite cookies.",
                            OrderIndex = 4,
                            SubCategoryId = 4,
                            Text = "Vad är en säker åtgärd mot CSRF?"
                        },
                        new
                        {
                            Id = 20,
                            Explanation = "Om DB läcker ska lösenord inte kunna läsas i klartext.",
                            OrderIndex = 5,
                            SubCategoryId = 4,
                            Text = "Varför ska man hasha lösenord i databasen?"
                        });
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "OrderIndex")
                        .IsUnique()
                        .HasFilter("[OrderIndex] IS NOT NULL");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Starka lösenord och multifaktor.",
                            Name = "Lösenord & MFA",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Känna igen bedrägerier.",
                            Name = "Phishing & social engineering",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Portar, DNS, brandväggar.",
                            Name = "Nätverksgrunder",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "HTTPS, cookies, vanliga webbsårbarheter.",
                            Name = "Webbsäkerhet",
                            OrderIndex = 2
                        });
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.UserResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAnswerOptionId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedAnswerOptionId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SubCategoryId");

                    b.ToTable("UserResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.AnswerOption", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.Question", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.SubCategory", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.SubCategory", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.UserResult", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyberQuiz.Infrastructure.Entities.AnswerOption", "SelectedAnswerOption")
                        .WithMany()
                        .HasForeignKey("SelectedAnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyberQuiz.Infrastructure.Entities.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyberQuiz.Infrastructure.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswerOption");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberQuiz.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CyberQuiz.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("CyberQuiz.Infrastructure.Entities.SubCategory", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
